name: tamz
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase: ^9.0.2
  cloud_firestore: ^3.1.7
  flutter_spinkit: ^5.1.0
  shared_preferences: ^2.0.12
  firebase_auth: ^3.3.6
  file_picker: ^4.3.2
  flutter_chat_ui:
  image_picker: ^0.8.4+5
  intl: ^0.17.0
  mime: ^1.0.1
  open_file: ^3.2.1
  uuid: ^3.0.5
  dropdown_formfield: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/languages/

  fonts:
    - family: news
      fonts:
        - asset: assets/fonts/news.ttf

    - family: omar
      fonts:
        - asset: assets/fonts/Omar.ttf
    
    - family: pun
      fonts:
        - asset: assets/fonts/pun.ttf

    - family: somar
      fonts:
        - asset: assets/fonts/Somar-Bold.otf

